name: Pull Request

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: set mtime
        run: |
          set +e
          git submodule foreach 'rev=HEAD; for f in $(git ls-tree -r -t --full-name --name-only "$rev") ; do     touch -t $(git log --pretty=format:%cd --date=format:%Y%m%d%H%M.%S -1 "$rev" -- "$f") "$f"; done'
          rev=HEAD; for f in $(git ls-tree -r -t --full-name --name-only "$rev") ; do     touch -t $(git log --pretty=format:%cd --date=format:%Y%m%d%H%M.%S -1 "$rev" -- "$f") "$f"; done

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: workspace-state
        uses: actions/cache@v2
        id: workspace-state
        with:
          path: |
            Build/SourcePackages/workspace-state.json
          key: ${{ runner.os }}-workspace-state-${{ hashFiles(format('**/xcshareddata/swiftpm/Package.resolved')) }}

      - name: source-packages-artifacts
        uses: actions/cache@v2
        id: source-packages-artifacts
        with:
          path: |
            Build/SourcePackages/artifacts
          key: ${{ runner.os }}-source-packages-artifacts-${{ hashFiles(format('**/xcshareddata/swiftpm/Package.resolved')) }}

      - name: source-packages-checkouts
        uses: actions/cache@v2
        id: source-packages-checkouts
        with:
          path: |
            Build/SourcePackages/checkouts
          key: ${{ runner.os }}-source-packages-checkouts-${{ hashFiles(format('**/xcshareddata/swiftpm/Package.resolved')) }}

      - name: source-packages-repositories
        uses: actions/cache@v2
        id: source-packages-repositories
        with:
          path: |
            Build/SourcePackages/repositories
          key: ${{ runner.os }}-source-packages-repositories-${{ hashFiles(format('**/xcshareddata/swiftpm/Package.resolved')) }}

      - name: build-products
        uses: actions/cache@v2
        id: build-products
        with:
          path: |
            Build/Build/Products
          key: ${{ runner.os }}-build-products-${{ hashFiles(format('**/xcshareddata/swiftpm/Package.resolved')) }}

      - name: Run Tests (No Cache)
        if: steps.workspace-state.outputs.cache-hit != 'true'
        run: bundle exec fastlane unit_test
      
      - name: Run Tests (Cache)
        if: steps.workspace-state.outputs.cache-hit == 'true'
        run: bundle exec fastlane unit_test skip_package_dependencies_resolution:true
