name: Pull Request

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: build-products
        uses: actions/cache@v2
        id: build-products
        with:
          path: |
            Build/Build/Products
          key: ${{ runner.os }}-build-products-${{ hashFiles(format('{0}/**/xcshareddata/swiftpm/Package.resolved', env.APP_DIR)) }}

      - name: source-packages-artifacts
        uses: actions/cache@v2
        id: source-packages-artifacts
        with:
          path: |
            Build/SourcePackages/artifacts
          key: ${{ runner.os }}-source-packages-artifacts-${{ hashFiles(format('{0}/**/xcshareddata/swiftpm/Package.resolved', env.APP_DIR)) }}

      - name: source-packages-checkouts
        uses: actions/cache@v2
        id: source-packages-checkouts
        with:
          path: |
            Build/SourcePackages/checkouts
          key: ${{ runner.os }}-source-packages-checkouts-${{ hashFiles(format('{0}/**/xcshareddata/swiftpm/Package.resolved', env.APP_DIR)) }}

      - name: source-packages-repositories
        uses: actions/cache@v2
        id: source-packages-repositories
        with:
          path: |
            Build/SourcePackages/repositories
          key: ${{ runner.os }}-source-packages-repositories-${{ hashFiles(format('{0}/**/xcshareddata/swiftpm/Package.resolved', env.APP_DIR)) }}

      - name: Run Tests (No Cache)
        if: steps.build-products.outputs.cache-hit != 'true'
        run: bundle exec fastlane unit_test
      
      - name: Run Tests (Cache)
        if: steps.build-products.outputs.cache-hit == 'true'
        run: bundle exec fastlane unit_test skip_package_dependencies_resolution:true
