name: Pull Request

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: workspace-state
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/Build/Products
            Build/SourcePackages
          key: ${{ runner.os }}-cache-${{ hashFiles(format('**/xcshareddata/swiftpm/Package.resolved')) }}

      - name: Run Tests (No Cache)
        if: steps.cache.outputs.cache-hit != 'true'
        run: bundle exec fastlane unit_test
      
      - name: Run Tests (Cache)
        if: steps.cache.outputs.cache-hit == 'true'
        run: bundle exec fastlane unit_test skip_package_dependencies_resolution:true
